<!doctype html>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>WoWGnome</title>
  <meta name="description" content="">
  <meta name="author" content="Fleya of EU Guldan">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="<?php echo $this->baseUrl('css/style.css?v=2'); ?>">
  <?php $this->headScript(Zend_View_Helper_HeadScript::FILE, $this->baseUrl('js/libs/modernizr-1.7.min.js'), 'set') ?>
  <?php echo $this->headScript(); ?>
</head>

<body>

  <div id="main" role="main">
    <?php echo $this->layout()->content; ?>
    <script id="jobTemplate" type="text/x-jQuery-tmpl">
        <section id="${name}">
        	<section class="metrics">
				<div class="metric">
            CPD
        	<img src="img/vector/up-red.png" alt="Delta" class="up" />
        	<p class="good">500</p>
        </div>
        	</section>
        	<img class="weather" src="img/weather/5.png" alt="Weather" />
        	<h1>${name}</h1>
        	<h2>${group} ${branch} ${team}</h2>
        </section>
    </script>
    <script id="violationTemplate" type="text/x-jQuery-tmpl">
		<div class="metric">
            CPD
        	<img src="img/vector/up-red.png" alt="Delta" class="up" />
        	<p class="good">500</p>
        </div>
	</script>
  </div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js"></script>
  <script>window.jQuery || document.write("<script src='js/libs/jquery-1.5.1.min.js'>\x3C/script>")</script>
  <script src="<?php echo $this->baseUrl('js/plugins.js'); ?>"></script>
  <script src="<?php echo $this->baseUrl('js/script.js'); ?>"></script>

  <!--[if lt IE 7 ]>
    <script src="js/libs/dd_belatedpng.js"></script>
    <script>DD_belatedPNG.fix("img, .png_bg"); </script>
  <![endif]-->

  <!-- GOOGLE TRACKING -->
  <script>
    var _gaq=[["_setAccount","UA-XXXXX-X"],["_trackPageview"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));
  </script>

  <!-- CORE INITIALIZATION -->
  <script>
  	Core.baseUrl = '<?php echo $this->baseUrl(); ?>';
  	Core.staticUrl = '<?php echo $this->baseUrl(); ?>';
  	(function($){
  	  	Load.load('js/dash.js');
  	})(jQuery);
  </script>

</body>
</html>